export const productosActionTypes = {
  AGREGAR_PRODUCTO : 'AGREGAR_PRODUCTO',
  AGREGAR_PRODUCTO_EXITO : 'AGREGAR_PRODUCTO_EXITO',
  AGREGAR_PRODUCTO_ERROR : 'AGREGAR_PRODUCTO_ERROR',
  COMENZAR_DESCARGA_PRODUCTOS: 'COMENZAR_DESCARGA_PRODUCTOS',
  DESCARGA_PRODUCTOS_EXITO: 'DESCARGA_PRODUCTOS_EXITO',
  DESCARGA_PRODUCTOS_ERROR: 'DESCARGA_PRODUCTOS_ERROR',
  OBTENER_PRODUCTO_ELIMINAR: 'OBTENER_PRODUCTO_ELIMINAR',
  PRODUCTO_ELIMINADO_EXITO: 'PRODUCTO_ELIMINADO_EXITO',
  PRODUCTO_ELIMINADO_ERROR: 'PRODUCTO_ELIMINADO_ERROR',
}